#!/bin/sh

# relies on intel_pstate
[ -d /sys/devices/system/cpu/intel_pstate ] || exit $NA

GOVERNOR="/sys/devices/system/cpu/cpu*/cpufreq/scaling_governor"

for f in $GOVERNOR ; do
  [ -w $f ] || exit $NA
done

case $1 in
    true)  echo powersave | tee $GOVERNOR;;
    false) echo ondemand | tee $GOVERNOR;;
    *) exit $NA;;
esac

exit 0
