#!/bin/sh

#
# This script adjusts the USB bluetooth device settings via the USB
# power control.  This simply sets this to "auto" for power saving and to "on"
# for non-power saving.   This has been shown to save about 1W on some
# systems.
#
# According to http://www.usb.org/developers/defined_class
#   USB wireless bluetooth devices have baseclass 0xe0, subclass 0x01,
#   protocol 0x01
#
# However this Intel Bluetooth 4.0 device uses baseclass 0xff, 
# which is 'Vendor specific'.  So we identify it by USB idProduct/idVendor


USB_BLUETOOTH_PM_ENABLE="${USB_BLUETOOTH_PM_ENABLE:-true}"

set_usb_bluetooth()
{
  USB_ID=8087:0a2b
  sysfs_path="$(dirname $(grep -l ${USB_ID%%:*} /sys/bus/usb/devices/*/idVendor | xargs dirname | xargs -i grep -l ${USB_ID##*:} {}/idProduct))"

  if [ -n "$sysfs_path" -a -d "$sysfs_path" ] ; then
    echo Setting $sysfs_path to $1
    echo $1 > $sysfs_path/power/control
  else
    exit 254
  fi

}

case "$1" in
	true) # powersaving on
		[ "$USB_BLUETOOTH_PM_ENABLE" = true ] && set_usb_bluetooth "auto"
		;;
	false) # powersaving off
		[ "$USB_BLUETOOTH_PM_ENABLE" = true ] && set_usb_bluetooth "on"
		;;
	*)
		exit 254
		;;
esac

exit 0
