#!/bin/sh

# Set the fingerprint scanner to power saving at all times.
# It's completely insecure and shouldn't be used.
# USB ids from:
# http://www.thinkwiki.org/wiki/Integrated_Fingerprint_Reader

FP_SCANNER_ID=138a:0097

set_usb_fps()
{
  sysfs_path="$(dirname $(grep -l ${FP_SCANNER_ID%%:*} /sys/bus/usb/devices/*/idVendor | xargs dirname | xargs -i grep -l ${FP_SCANNER_ID##*:} {}/idProduct))"

  if [ -n "$sysfs_path" -a -d "$sysfs_path" ] ; then
    echo Setting $sysfs_path to $1
    echo $1 > $sysfs_path/power/control
  else
    exit 254
  fi
}

case "$1" in
  true|false) # powersaving on always
    set_usb_fps "auto"
    ;;
  *)
    exit 254
    ;;
esac

exit 0
